FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --chown=1001:root target/*-runner /work/application

# Set environment variables for database connection
ENV QUARKUS_DATASOURCE_DB_KIND=postgresql
ENV QUARKUS_DATASOURCE_USERNAME=admin
ENV QUARKUS_DATASOURCE_PASSWORD=admin
ENV QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/casino
ENV QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
ENV QUARKUS_HIBERNATE_ORM_LOG_SQL=true
ENV QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT=import.sql

EXPOSE 8080

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
